
name: resuable Deploy
on: 
    workflow_call: 
        inputs: 
            artifact-name: 
                description: the name of the artifact files
                required: false
                default: dist
                type: string
     #   secrets: 
      #      some-secrets: 
       #         required: true
        outputs: 
            result: 
                description: the result of deplyment
                value: ${{ jobs.deploy.outputs.outcome }}
jobs: 
  deploy:
        outputs: 
            #outcome: ${{ steps.set-result.outputs.step-result }}
            outcome: $GITHUB_OUTPUT
        runs-on: ubuntu-latest
        steps: 
        - name: Get build artifacts
          uses: actions/download-artifact@v3
          with: 
           name: ${{ inputs.artifact-name }}
        - name: list files in the output
          run: ls
        - name: output information
          run: echo "deploying and uploading.."
        - name: Set Result Output
          id: set-result
          run: echo "step-result=success" >> $GITHUB_OUTPUT
